services:
  daq:
    container_name: daq
    image: gmazzitelli/daq:1.0
    ports:
      - 8888:8888

    user: root                
    working_dir: /home/jovyan/work
    privileged: true

    environment:
      - GRANT_SUDO=yes
      - REPO_LIST=sft.cern.ch
    volumes:
      - /Volumes/WC:/home/jovyan/work/data
      - "$PWD/../:/home/jovyan/work"
      - daq:/cvmfs 
#      - ./mount_cvmfs.sh:/usr/bin/mount_cvmfs.sh
    stdin_open: true  
    tty: true 
#    command: [tini -g -- start-notebook.py && exec sudo /usr/bin/mount_cvmfs.sh]

  cvmfs:
    image: registry.cern.ch/cvmfs/service
    restart: unless-stopped
    container_name: cvmfs
    environment: 
      CVMFS_CLIENT_PROFILE: 'single'
      CVMFS_REPOSITORIES: 'sft.cern.ch'
    privileged: true
    devices:
       - /dev/fuse
    volumes:
       - daq:/cvmfs
volumes:
  daq:
    driver: local
